### ISSUE TITLE
关于课表导出 ics

### ISSUE THREAD

**Issue by Robotxm** [xdlinux/xidian-scripts#4]
之前 commit 时用的是今日校园 app 的 API，上学期确实能导出。不过到现在学校还没开放今日校园 app 的课表查看，所以相当于这个玩意儿目前废掉了。后面可能得用教务系统的 API 重写一下。

**Comment by frankli0324** [comment]
嗯。。这两天想补呢没时间。。。
总之呢
```
ses = auth.ids.get_login_session(
    'http://ehall.xidian.edu.cn:80//appShow', '18130500303', 'lixuanzhe0324')
ses.get('http://ehall.xidian.edu.cn//appShow?appId=4770397878132218', headers={
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
})

x = ses.post('http://ehall.xidian.edu.cn/jwapp/sys/wdkb/modules/xskcb/xskcb.do', headers={  # 学生课程表
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Accept': 'application/json, text/javascript, */*; q=0.01'
},
    data={'XNXQDM': '2018-2019-2'}
).json()

for i in x['datas']['xskcb']['rows']:
	课程名是 i['KCM']
	节数是 i['KSJC']
	教室是 i['JASMC']
	i['SKZC']的第i位表示第几周有没有这节课
```
有时间的话。。pr一下？

**Comment by frankli0324** [comment]
ses = auth.ids.get_login_session(
    'http://ehall.xidian.edu.cn:80//appShow', '用户名', '密码')
ses.get('http://ehall.xidian.edu.cn//appShow?appId=4770397878132218', headers={
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
})

x = ses.post('http://ehall.xidian.edu.cn/jwapp/sys/wdkb/modules/xskcb/xskcb.do', headers={  # 学生课程表
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Accept': 'application/json, text/javascript, */*; q=0.01'
},
    data={'XNXQDM': '2018-2019-2'}
).json()

for i in x['datas']['xskcb']['rows']:
	课程名是 i['KCM']
	节数是 i['KSJC']
	教室是 i['JASMC']
	i['SKZC']的第i位表示第几周有没有这节课

**Comment by frankli0324** [comment]
嗯。。。前几天我也是想整一个。。然而没时间
总之呢
```python
ses = auth.ids.get_login_session(
    'http://ehall.xidian.edu.cn:80//appShow', 'username', 'pwd')
ses.get('http://ehall.xidian.edu.cn//appShow?appId=4770397878132218', headers={
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
})

x = ses.post('http://ehall.xidian.edu.cn/jwapp/sys/wdkb/modules/xskcb/xskcb.do', headers={  # 学生课程表
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Accept': 'application/json, text/javascript, */*; q=0.01'
},
    data={'XNXQDM': '2018-2019-2'}
).json()

for i in x['datas']['xskcb']['rows']:
	课程名是 i['KCM']
	节数是 i['KSJC']
	教室是 i['JASMC']
	i['SKZC']的第i位表示第几周有没有这节课
```
有时间pr一下呗
@Robotxm

**Comment by Robotxm** [comment]
@frankli0324 仔细看了一下教务处的数据，感觉极其不友好。有的课会有不同的上课时间，KSJC 和 JSJC（开始节次、结束节次）只有其中一个时间的。可能整起来比较麻烦了。

**Comment by Robotxm** [comment]
@frankli0324 已 pr。教务处的这个数据有点烦人。

**Comment by frankli0324** [comment]
嗯。。它同一节课同一周内不同时间是看作不同的课程的

**Comment by frankli0324** [comment]
话说我看了半晚上没看懂你这时间表咋排的。。。
我重构一下？
@Robotxm 
还有，加个QQ吧
